version: "3.9"

services:
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
          LETSENCRYPT_HOST: ${APP_HOSTNAME}
          VIRTUAL_HOST: ${APP_HOSTNAME}
          VIRTUAL_PORT: ${SERVER_PORT}
        depends_on:
          - postgres
        command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && node /app/server/src/index.js"]
        networks:
          - awesome

    postgres:
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - awesome

    nginx-proxy:
      image: nginxproxy/nginx-proxy
      container_name: nginx-proxy
      restart: always
      ports:
        - 80:80
        - 443:443
      depends_on:
        - server
      volumes:
        - conf:/etc/nginx/conf.d
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - certs:/etc/nginx/certs:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro
      networks:
      - awesome

    acme-companion:
      image: nginxproxy/acme-companion
      container_name: nginx-proxy-acme
      restart: always
      depends_on:
        - nginx-proxy
      volumes_from:
        - nginx-proxy
      volumes:
        - certs:/etc/nginx/certs:rw
        - acme:/etc/acme.sh
        - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  awesome:
    driver: bridge
