export enum PATHNAMES {
  HOME = '/',
  LOGIN = '/login',
  REGISTRATION = '/registration',
  ERROR_500 = '/500',
  ERROR_404 = '*',
  GALAXIAN = '/galaxian',
  GAMEOVER = '/gameover',
  LEADERBOARD = '/leaderboard',
  FORUM = '/forums',
  TOPIC = '/forums/:id',
  COMMENT = '/forums/:id/:id',
  PROFILE = '/profile',
  PROFILE_EDIT = '/profile/edit',
  PASSWORD_EDIT = '/profile/password',
  PRESENTATION = '/presentation',
  GAME = '/game',
}
